### ISSUE TITLE
New error on working workflow

### ISSUE THREAD

**Issue by sbrunner** [ridedott/merge-me-action#505]
**How would you describe the issue?**

From this weekend I have this error:

```
Automatic merges enabled for GitHub login: dependabot-preview[bot].
Found pull request information: {"reviewEdges":[{"node":{"state":"APPROVED"}}]}.
An error ocurred while merging the Pull Request. This is usually caused by the base branch being out of sync with the target branch. In this case, the base branch must be rebased. Some tools, such as Dependabot, do that automatically.
##[error]An unexpected error occurred: Required status check "Continuous integration" is in progress., GraphqlError: Required status check "Continuous integration" is in progress.
    at key (/home/runner/work/_actions/ridedott/dependabot-auto-merge-action/master/node_modules/@octokit/graphql/dist-node/index.js:42:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at approveAndMergePullRequestMutation (/home/runner/work/_actions/ridedott/dependabot-auto-merge-action/master/src/common/merge.ts:40:9)
    at Object.mergeWithRetry (/home/runner/work/_actions/ridedott/dependabot-auto-merge-action/master/src/common/merge.ts:49:14)
    at Object.logInfo (/home/runner/work/_actions/ridedott/dependabot-auto-merge-action/master/src/eventHandlers/pullRequest/index.ts:86:5).
```

**How can we reproduce the issue?**

Run this workflow:
https://github.com/mapfish/mapfish-print/blob/master/.github/workflows/dependabot-auto-merge.yaml

In // of a required and running workflow

**What are the expected results?**

Validate the pull request

**What are the actual results?**

Error in the workflow, e.-g.:

https://github.com/mapfish/mapfish-print/pull/1453/checks?check_run_id=1020852174

**How much does it hurt?**

It makes this action unusable for us...

**Comment by merlinnot** [comment]
@sbrunner Thanks for reporting! We've found the issue, will pick it up soon. Sorry for the inconvenience!

**Comment by sbrunner** [comment]
Thanks, it's working well :-)

**Comment by JrSchild** [comment]
Glad to hear :)
